TransportlyProject/TransportLy.MVC/Models/ErrorViewModel.cs
using System;

namespace TransportLy.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TransportlyProject/TransportLy.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TransportLy.MVC.Models;
using TransportLy.Application.DTOs;
using TransportLy.Domain.Contracts;

namespace TransportLy.MVC.Controllers
{
    public class HomeController : Controller
    {
        IOrderManager _orderManager;
        public HomeController(IOrderManager orderManager)
        {
            _orderManager = orderManager;
        }
       
        public IActionResult Index()
        {
           
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TransportlyProject/TransportLy.MVC/Controllers/InventoryManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TransportLy.Application.DTOs;
using TransportLy.Application.Exceptions;
using TransportLy.Domain.Contracts;
using TransportLy.Domain.Entities;

namespace TransportLy.MVC.Controllers
{
    public class InventoryManagerController : Controller
    {
        IFlightItinerariManager _manager;
        IManager<AirPort> _airportManager;
        IManager<AirPlain> _airplainManager;

        public InventoryManagerController(IFlightItinerariManager manager, IManager<AirPort> airportManager, IManager<AirPlain> airplainManager)
        {
            _manager = manager;
            _airplainManager = airplainManager;
            _airportManager = airportManager;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AddToFlight(int id,int flightId)
        {
            try
            {
                _manager.AddOrderToFlight(flightId, id);
                return RedirectToAction("FlightOrders", "InventoryManager", routeValues: new { @id = flightId });
            }
            catch (FlightOrderException ex)
            {
                //Log
                return RedirectToAction("FlightOrders", "InventoryManager", routeValues: new { @id = flightId });

            }
            catch (Exception)
            {

                throw;
            }
            
        }
        public IActionResult flights()
        {
            return View(_manager.Find());
        }
        public IActionResult FlightOrders(int id)
        {

            return View(_manager.GetFlighOrders(id));
        }
        public IActionResult flight()
        {
            ViewBag.Airports = _airportManager.Find().ToList();
            ViewBag.Airplains = _airplainManager.Find().ToList();
            return View();
        }
        [HttpPost]
        public IActionResult flight(FlightItinerariDTO flight)
        {
            ViewBag.Airports = _airportManager.Find().ToList();
            ViewBag.Airplains = _airplainManager.Find().ToList();
            try
            {
                _manager.Add(flight);
                return RedirectToAction("flights", "InventoryManager");
            }
            catch (FlightException ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }
            catch (Exception exp)
            {
                //Log message
                return View();
            }

            return View();
        }

    }
}

TransportlyProject/TransportLy.MVC/Controllers/LogInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using System.Text;
using TransportLy.Application.DTOs;
using TransportLy.Domain.Entities;
using TransportLy.Domain.Contracts;

namespace TransportLy.MVC.Controllers
{
    public class LogInController : Controller
    {

        IManager<User> _userManager;
        public LogInController(IManager<User> userManager)
        {
            _userManager = userManager;
        }

      
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult LogOut()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(User user)
        {
            if (ModelState.IsValid)
            {
                var obj = _userManager.Find(a => a.UserName.Equals(user.UserName) && a.Password.Equals(user.Password)).FirstOrDefault();
                if (obj != null)
                {
                    HttpContext.Session.Set("UserName", Encoding.ASCII.GetBytes(obj.UserName));
                    HttpContext.Session.Set("Role", Encoding.ASCII.GetBytes(obj.RoleId.ToString()));
                    HttpContext.Session.Set("CustomerId", Encoding.ASCII.GetBytes(obj.CustomerId.HasValue ? obj.CustomerId.Value.ToString() : "0"));
                    return RedirectToAction("Index", "Home");


                }
            }
            return View(user);
        }
    }
}

TransportlyProject/TransportLy.MVC/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TransportLy.Application.DTOs;
using TransportLy.Application.Exceptions;
using TransportLy.Application.Helpers;
using TransportLy.Domain.Contracts;
using TransportLy.Domain.Entities;

namespace TransportLy.MVC.Controllers
{
    public class OrderController : Controller
    {
        IOrderManager _orderManager;
        IManager<AirPort> _airportManager;
        IRandomCodeGenerator _randomCodeGenerator;
        public OrderController(IOrderManager orderManager, IManager<AirPort> airportManager,IRandomCodeGenerator randomCodeGenerator)
        {
            _orderManager = orderManager;
            _airportManager = airportManager;
            _randomCodeGenerator = randomCodeGenerator;
        }
        public IActionResult Index(int id)
        {
            ViewBag.Airports = _airportManager.Find().ToList();
            OrderDTO orderDTO = new OrderDTO(id,_randomCodeGenerator);
            return View(orderDTO);
        }
        [HttpPost]
        public IActionResult SubmitOrder(OrderDTO orderDTO)
        {
            try
            {
                orderDTO.SubmitDate = DateTime.Now;
                if (orderDTO.OrderDate == DateTime.MinValue) orderDTO.OrderDate = DateTime.Now;
                orderDTO.OrderCode = _randomCodeGenerator.GenerateCode(20);
                _orderManager.Add(orderDTO);
                ViewBag.Message = $"Your Order Is submited with this Code:[{orderDTO.OrderCode}]";
                return View();
            }
            catch(OrderException ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }
            catch (Exception )
            {
                //Log Error
                ViewBag.Message = $"OPPS Error !!!!";
                return View();

            }
            
        }
    }
}

TransportlyProject/TransportLy.MVC/Controllers/ShippingManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TransportLy.Domain.Contracts;

namespace TransportLy.MVC.Controllers
{
    public class ShippingManagerController : Controller
    {
        IFlightItinerariManager _manager;
        public ShippingManagerController(IFlightItinerariManager manager)
        {
            _manager = manager;
        }
        public IActionResult Flights()
        {
            return View(_manager.Find());
        }
        public IActionResult FlightOrders(int id)
        {
            return View(_manager.GetFlighOrders(id));
        }
    }
}

TransportlyProject/TransportLy.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

TransportlyProject/TransportLy.MVC/Views/Home/Login.cshtml
@{
    ViewData["Title"] = "Login";
}

<h1>Login</h1>

TransportlyProject/TransportLy.MVC/Views/InventoryManager/FlightOrders.cshtml
@model TransportLy.Application.DTOs.FlightOrdersDTO
@{
    ViewData["Title"] = "FlightOrders";
}
<h3>Flight Orders details</h3>
<table class="table">
    <thead>
        <tr>
            <th>
                Flight date
            </th>
            <th>
                Airport name
            </th>
            <th>
                Aiplane name
            </th>
            <th>
                Count
            </th>
            <th>
                Sum
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                @Model.FlightDate.Date
            </td>
            <td>
                @Model.AirPort.Name
            </td>
            <td>
                @Model.AirPlain.Name
            </td>
            <td>
                @Model.OrdersCount
            </td>
            <td>
                @Model.OrdersSum
            </td>
        </tr>
    </tbody>
</table>
<hr />
<h3>Assigned Orders</h3>
<table class="table">
    <thead>
        <tr>
            <th>
                Order date
            </th>
            <th>
                Quantity
            </th>
            <th>
                Code
            </th>
            <th>
                Type
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.AssignedOrders)
        {
            <tr>
                <td>
                    @item.OrderDate.Date
                </td>
                <td>
                    @item.Quantity
                </td>
                <td>
                    @item.OrderCode
                </td>
                <td>
                    @item.ShippingType
                </td>
            </tr>
        }
    </tbody>
</table>
<hr />
<h3>Available Orders</h3>
<table class="table">
    <thead>
        <tr>
            <th>
                Order date
            </th>
            <th>
                Quantity
            </th>
            <th>
                Code
            </th>
            <th>
                Type
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.PotentialOrders)
        {
            <tr>
                <td>
                    @item.OrderDate.Date
                </td>
                <td>
                    @item.Quantity
                </td>
                <th>
                    @item.OrderCode
                </th>
                <td>
                    @item.ShippingType
                </td>
                <td>
                    <a asp-action="AddToFlight" asp-route-id="@item.Id" asp-route-flightId="@Model.Id">Add to flight</a>
                </td>
            </tr>
        }
    </tbody>
</table>

TransportlyProject/TransportLy.MVC/Views/InventoryManager/flight.cshtml
@model TransportLy.Application.DTOs.FlightItinerariDTO
@{
    ViewData["Title"] = "flight";
}


@using (Html.BeginForm("flight", "InventoryManager", FormMethod.Post))
{
    <fieldset>
        <legend>New flight</legend>

        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        @if (@ViewBag.Message != null)
        {
            <div style="border: 1px solid red">
                @ViewBag.Message
            </div>
        }
    <table>
        <tr>
            <td>@Html.LabelFor(a => a.FlightDate)</td>
            <td>@Html.TextBoxFor(a => a.FlightDate, new { @class = "datefield", type = "date" })</td>
            <td>@Html.ValidationMessageFor(a => a.FlightDate)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.AirPortId)</td>
            <td>@Html.DropDownListFor(a => a.AirPortId, new SelectList(ViewBag.Airports, "Id", "Name"))</td>

        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.AirPlainId)</td>
            <td>@Html.DropDownListFor(a => a.AirPlainId, new SelectList(ViewBag.Airplains, "Id", "Name"))</td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Submit fligh" />
            </td>
            <td></td>
        </tr>
    </table>
        
    </fieldset>
}

TransportlyProject/TransportLy.MVC/Views/InventoryManager/flights.cshtml
@model IEnumerable<TransportLy.Application.DTOs.FlightItinerariDTO>
@{
    ViewData["Title"] = "flights";
}
<h1>Flights</h1>
<table class="table">
    <thead>
        <tr>
            <th>
               Flight date
            </th>
            <th>
               Airport name
            </th>
            <th>
               Aiplane name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FlightDate.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AirPort.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AirPlain.Name)
                </td>
               
                <td>
                    <a asp-action="FlightOrders" asp-route-id="@item.Id">Edit</a> 
                </td>
            </tr>
        }
    </tbody>
</table>

TransportlyProject/TransportLy.MVC/Views/LogIn/Index.cshtml
@model TransportLy.Domain.Entities.User
@{
    ViewData["Title"] = "Login";
}

@using (Html.BeginForm("Index", "Login", FormMethod.Post))
{
    <fieldset>
        <legend>Login</legend>

        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        @if (@ViewBag.Message != null)
        {
            <div style="border: 1px solid red">
                @ViewBag.Message
            </div>
        }
        <table>
            <tr>
                <td>@Html.LabelFor(a => a.UserName)</td>
                <td>@Html.TextBoxFor(a => a.UserName)</td>
                <td>@Html.ValidationMessageFor(a => a.UserName)</td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(a => a.Password)
                </td>
                <td>
                    @Html.PasswordFor(a => a.Password)
                </td>
                <td>
                    @Html.ValidationMessageFor(a => a.Password)
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <input type="submit" value="Index" />
                </td>
                <td></td>
            </tr>
        </table>
    </fieldset>
}

TransportlyProject/TransportLy.MVC/Views/Order/Index.cshtml
@model TransportLy.Application.DTOs.OrderDTO
@{
    ViewData["Title"] = "New Order";
}
@using (Html.BeginForm("SubmitOrder", "Order", FormMethod.Post))
{
<fieldset>
    <legend>New Order</legend>

    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @if (@ViewBag.Message != null)
    {
        <div style="border: 1px solid red">
            @ViewBag.Message
        </div>
    }
    @Html.HiddenFor(a => a.CustomerId)
<table>
    <tr>
        <td>@Html.LabelFor(a => a.Quantity)</td>
        <td>@Html.TextBoxFor(a => a.Quantity, new { @type = "number" })</td>
        <td>@Html.ValidationMessageFor(a => a.Quantity)</td>
    </tr>
    <tr>
        <td>@Html.LabelFor(a => a.ShippingType)</td>
        <td>@Html.DropDownListFor(a => a.ShippingType, Enum.GetNames(typeof(TransportLy.Domain.Enumes.ShippingTypeEnum)).Select(e => new SelectListItem { Text = e }))</td>
    </tr>
    <tr>
        <td>@Html.LabelFor(a => a.OrderDate)</td>
        <td>@Html.TextBoxFor(a => a.OrderDate, new { @class = "datefield", type = "date" })</td>
        <td>@Html.ValidationMessageFor(a => a.OrderDate)</td>
    </tr>
    <tr>
        <td>@Html.LabelFor(a => a.AirportId)</td>
        <td>@Html.DropDownListFor(a => a.AirportId,new SelectList(ViewBag.Airports, "Id", "Name"))</td>
        
    </tr>
    <tr>
        <td></td>
        <td>
            <input type="submit" value="Submit Order" />
        </td>
        <td></td>
    </tr>
</table>
</fieldset>
}

<script>
  $(document).ready(function() {
      $("#Order Date").datepicker();
  });
</script>

TransportlyProject/TransportLy.MVC/Views/Order/SubmitOrder.cshtml
@{
    ViewData["Title"] = "SubmitOrder";
}

<h3>@ViewBag.Message</h3>

TransportlyProject/TransportLy.MVC/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TransportLy.MVC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TransportLy</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @{
                            byte[] userRole;
                            byte[] userName;
                            byte[] bytecustomerId;
                            int customerId = 0;
                            HttpContextAccessor.HttpContext.Session.TryGetValue("Role", out userRole);
                            HttpContextAccessor.HttpContext.Session.TryGetValue("UserName", out userName);
                            HttpContextAccessor.HttpContext.Session.TryGetValue("CustomerId", out bytecustomerId);
                            if (bytecustomerId != null)
                            {
                                int.TryParse(System.Text.Encoding.UTF8.GetString(bytecustomerId), out customerId);
                            }
                            if (userName == null)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Log In</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="LogOut">Log out</a>
                                </li>

                            }
                            if (userRole != null && System.Text.Encoding.UTF8.GetString(userRole).Equals("1"))
                            {
                                <li class="nav-item">

                                    <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index" asp-route-id="@customerId">New Order</a>

                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="list">your Orders</a>
                                </li>
                            }
                            if (userRole != null && System.Text.Encoding.UTF8.GetString(userRole).Equals("2"))
                            {
                                <li class="nav-item">

                                    <a class="nav-link text-dark" asp-area="" asp-controller="ShippingManager" asp-action="flights">Flights</a>
                                </li>

                            }
                            if (userRole != null && System.Text.Encoding.UTF8.GetString(userRole).Equals("3"))
                            {
                                <li class="nav-item">

                                    <a class="nav-link text-dark" asp-area="" asp-controller="InventoryManager" asp-action="flights">Flights</a>


                                </li>
                                <li class="nav-item">

                                    <a class="nav-link text-dark" asp-area="" asp-controller="InventoryManager" asp-action="flight">Add Flights</a>


                                </li>

                            }
                            if (userName != null)
                            {
                                <li class="nav-item">

                                    <span class="navbar-text text-info">[@System.Text.Encoding.UTF8.GetString(userName)]</span>

                                </li>

                            }

                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - TransportLy.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

TransportlyProject/TransportLy.MVC/Views/ShippingManager/FlightOrders.cshtml
@model TransportLy.Application.DTOs.FlightOrdersDTO
@{
    ViewData["Title"] = "FlightOrders";
}
<h3>Flight Orders details</h3>
<table class="table">
    <thead>
        <tr>
            <th>
                Flight date
            </th>
            <th>
                Airport name
            </th>
            <th>
                Aiplane name
            </th>
            <th>
                Count
            </th>
            <th>
                Sum
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                @Model.FlightDate.Date
            </td>
            <td>
                @Model.AirPort.Name
            </td>
            <td>
                @Model.AirPlain.Name
            </td>
            <td>
                @Model.OrdersCount
            </td>
            <td>
                @Model.OrdersSum
            </td>
        </tr>
    </tbody>
</table>
<hr />
<h3>Assigned Orders</h3>
<table class="table">
    <thead>
        <tr>
            <th>
                Order date
            </th>
            <th>
                Quantity
            </th>
            <th>
                Code
            </th>
            <th>
                Type
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.AssignedOrders)
        {
            <tr>
                <td>
                    @item.OrderDate.Date
                </td>
                <td>
                    @item.Quantity
                </td>
                <td>
                    @item.OrderCode
                </td>
                <td>
                    @item.ShippingType
                </td>
            </tr>
        }
    </tbody>
</table>

TransportlyProject/TransportLy.MVC/Views/ShippingManager/Flights.cshtml
@model IEnumerable<TransportLy.Application.DTOs.FlightItinerariDTO>
@{
    ViewData["Title"] = "flights";
}
<h1>Flights</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                Flight date
            </th>
            <th>
                Airport name
            </th>
            <th>
                Aiplane name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FlightDate.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AirPort.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AirPlain.Name)
                </td>

                <td>
                    <a asp-action="FlightOrders" asp-route-id="@item.Id">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>